### ISSUE TITLE
Repository - Source Files

### ISSUE THREAD

**Issue by jwood36** [joshSawYou/CIS255_Vehicle#6]
None of your Source Files are being committed to the repository.

Your *.class files but I can't do anything with the class files, I need the source code files.

Send me an email as soon as you get the Source Code Files placed in your repository, so I can evaluate that portion of Task #2.

**Comment by joshSawYou** [comment]
Are you referring to the “.java” file? If so, it is already in there and it’s called "CIS255_Vehicle.java.” If not, please tell me what you’re referring to.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: jwood36 ***@***.***>
Sent: Thursday, July 20, 2023 9:41:19 PM
To: joshSawYou/CIS255_Vehicle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [joshSawYou/CIS255_Vehicle] Repository - Source Files (Issue #6)


CAUTION: This message did not originate from Jefferson State.

None of your Source Files are being committed to the repository.

Your *.class files but I can't do anything with the class files, I need the source code files.

Send me an email as soon as you get the Source Code Files placed in your repository, so I can evaluate that portion of Task #2<https://github.com/joshSawYou/CIS255_Vehicle/issues/2>.

**Comment by joshSawYou** [comment]
I had all of my source code in that repository before task #2 was due, it was simply all in one file. I have since separate all of these files and put them in the github repository as well as severely updated my code.
________________________________
From: jwood36 ***@***.***>
Sent: Thursday, July 20, 2023 10:41 PM
To: joshSawYou/CIS255_Vehicle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [joshSawYou/CIS255_Vehicle] Repository - Source Files (Issue #6)


CAUTION: This message did not originate from Jefferson State.

None of your Source Files are being committed to the repository.

Your *.class files but I can't do anything with the class files, I need the source code files.

Send me an email as soon as you get the Source Code Files placed in your repository, so I can evaluate that portion of Task #2<https://github.com/joshSawYou/CIS255_Vehicle/issues/2>.

**Comment by joshSawYou** [comment]
All of my source code was in the repository; it was simply all in one file. I have since separated each class into its own *.java file and placed them in the github repository.
